#!/usr/bin/env python3
"""Generate CATALOG.md — the library's self-navigating index — from asset metadata.

Durability: this is the mechanism that keeps agent.librarian from rotting. It reads every
creation's _meta.json (+ toolspec.json for effects) and every template/lesson, and emits one
grouped, description-fidelity index. Run it after adding or renaming any asset; the router
reads the output, never a hand-maintained list.

Harness-neutral and dependency-free (stdlib only), so it survives the SeeD-vanishes test:
anyone with python3 and a clone can regenerate the catalog.

Usage: python3 scripts/build-catalog.py   (run from the library root)
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CREATIONS = ROOT / "creations"
TEMPLATES = ROOT / "templates"
LESSONS = ROOT / "lessons"
OUT = ROOT / "CATALOG.md"

KIND_ORDER = ["skill", "agent", "hook"]


def read_json(p: Path):
    try:
        return json.loads(p.read_text())
    except Exception:
        return {}


def creation_row(d: Path):
    meta = read_json(d / "_meta.json")
    cid = meta.get("id", d.name)
    kind = meta.get("kind", cid.split(".")[0])
    parts = cid.split(".")
    domain = parts[1] if len(parts) > 2 else (parts[1] if len(parts) > 1 else "-")
    desc = (meta.get("description") or "").strip().replace("\n", " ")
    effects = ""
    ts = d / "toolspec.json"
    if ts.exists():
        effects = read_json(ts).get("effects", "")
    return {"id": cid, "kind": kind, "domain": domain, "desc": desc, "effects": effects,
            "status": meta.get("status", "active"),
            "superseded_by": meta.get("superseded_by", "")}


def collect_creations():
    rows = []
    if CREATIONS.is_dir():
        for d in sorted(CREATIONS.iterdir()):
            if d.is_dir() and (d / "_meta.json").exists():
                rows.append(creation_row(d))
    return rows


def collect_patterns():
    out = []
    pdir = TEMPLATES / "patterns"
    if pdir.is_dir():
        for f in sorted(pdir.glob("*.pattern.json")):
            data = read_json(f)
            out.append({"id": data.get("id", f.stem), "intent": (data.get("intent") or "").strip(),
                        "status": data.get("status", "active"),
                        "superseded_by": data.get("superseded_by", "")})
    return out


def first_paragraph(md: Path) -> str:
    if not md.exists():
        return ""
    for block in md.read_text().split("\n\n"):
        b = block.strip()
        if b and not b.startswith("#"):
            return re.sub(r"\s+", " ", b)[:200]
    return ""


def collect_lessons():
    out = []
    if LESSONS.is_dir():
        for f in sorted(LESSONS.glob("*.md")):
            status = "invalidated" if "**Invalidated" in f.read_text() else "active"
            out.append({"name": f.stem, "hook": first_paragraph(f), "status": status})
    return out


def live(rows):
    """Rows the main sections list: active + incubating; deprecated/invalidated render
    in the lifecycle section; retired assets are absent from the catalog entirely."""
    return [r for r in rows if r["status"] in ("active", "incubating")]


def badge(row) -> str:
    return " _(incubating)_" if row["status"] == "incubating" else ""


def render(creations, patterns, lessons) -> str:
    lines = []
    lines.append("# CATALOG — the library index (generated)\n")
    lines.append("> **Generated by `scripts/build-catalog.py` — do not hand-edit.** "
                 "Regenerate after adding or renaming any asset. `agent.librarian` routes "
                 "from this file, so it must reflect what is on disk, not memory.\n")

    live_c, live_p, live_l = live(creations), live(patterns), live(lessons)
    dep_c = [r for r in creations if r["status"] == "deprecated"]
    dep_p = [r for r in patterns if r["status"] == "deprecated"]
    inv_l = [r for r in lessons if r["status"] == "invalidated"]
    graveyard = len(dep_c) + len(dep_p) + len(inv_l)
    grave_note = f" · {graveyard} deprecated/invalidated (see Lifecycle)" if graveyard else ""
    lines.append(f"Totals: {len(live_c)} creations · {len(live_p)} patterns · "
                 f"{len(live_l)} lessons{grave_note}.\n")

    # Creations grouped by kind, then domain
    for kind in KIND_ORDER:
        krows = [r for r in live_c if r["kind"] == kind]
        if not krows:
            continue
        lines.append(f"\n## {kind}s\n")
        domains = sorted({r["domain"] for r in krows})
        for dom in domains:
            drows = [r for r in krows if r["domain"] == dom]
            lines.append(f"\n### {dom}\n")
            for r in sorted(drows, key=lambda x: x["id"]):
                eff = f" _(effects: {r['effects']})_" if r["effects"] else ""
                lines.append(f"- **`{r['id']}`**{eff}{badge(r)} — {r['desc']}")

    # Patterns
    if live_p:
        lines.append("\n## patterns\n")
        for p in live_p:
            lines.append(f"- **`{p['id']}`**{badge(p)} — {p['intent']}")

    # Lessons
    if live_l:
        lines.append("\n## lessons\n")
        for l in live_l:
            lines.append(f"- **`{l['name']}`** — {l['hook']}")

    # Lifecycle graveyard — deprecated assets with their successors, invalidated lessons
    if graveyard:
        lines.append("\n## lifecycle: deprecated & invalidated\n")
        lines.append("> Kept for lineage holders; do not route new work here.\n")
        for r in dep_c:
            lines.append(f"- **`{r['id']}`** (creation) — superseded by `{r['superseded_by']}`")
        for r in dep_p:
            lines.append(f"- **`{r['id']}`** (pattern) — superseded by `{r['superseded_by']}`")
        for r in inv_l:
            lines.append(f"- **`{r['name']}`** (lesson) — invalidated; see its dated note")

    lines.append("")
    return "\n".join(lines)


def main():
    creations = collect_creations()
    patterns = collect_patterns()
    lessons = collect_lessons()
    OUT.write_text(render(creations, patterns, lessons))
    print(f"CATALOG.md: {len(creations)} creations, {len(patterns)} patterns, "
          f"{len(lessons)} lessons")


if __name__ == "__main__":
    main()
