#!/usr/bin/env python3
"""Generate CATALOG.md — the library's self-navigating index — from asset metadata.

Durability: this is the mechanism that keeps agent.librarian from rotting. It reads every
creation's _meta.json (+ toolspec.json for effects) and every template/lesson, and emits one
grouped, description-fidelity index. Run it after adding or renaming any asset; the router
reads the output, never a hand-maintained list.

Harness-neutral and dependency-free (stdlib only), so it survives the SeeD-vanishes test:
anyone with python3 and a clone can regenerate the catalog.

Usage: python3 scripts/build-catalog.py   (run from the library root)
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CREATIONS = ROOT / "creations"
TEMPLATES = ROOT / "templates"
LESSONS = ROOT / "lessons"
OUT = ROOT / "CATALOG.md"

KIND_ORDER = ["skill", "agent", "hook"]


def read_json(p: Path):
    try:
        return json.loads(p.read_text())
    except Exception:
        return {}


def creation_row(d: Path):
    meta = read_json(d / "_meta.json")
    cid = meta.get("id", d.name)
    kind = meta.get("kind", cid.split(".")[0])
    parts = cid.split(".")
    domain = parts[1] if len(parts) > 2 else (parts[1] if len(parts) > 1 else "-")
    desc = (meta.get("description") or "").strip().replace("\n", " ")
    effects = ""
    ts = d / "toolspec.json"
    if ts.exists():
        effects = read_json(ts).get("effects", "")
    return {"id": cid, "kind": kind, "domain": domain, "desc": desc, "effects": effects}


def collect_creations():
    rows = []
    if CREATIONS.is_dir():
        for d in sorted(CREATIONS.iterdir()):
            if d.is_dir() and (d / "_meta.json").exists():
                rows.append(creation_row(d))
    return rows


def collect_patterns():
    out = []
    pdir = TEMPLATES / "patterns"
    if pdir.is_dir():
        for f in sorted(pdir.glob("*.pattern.json")):
            data = read_json(f)
            out.append({"id": data.get("id", f.stem), "intent": (data.get("intent") or "").strip()})
    return out


def first_paragraph(md: Path) -> str:
    if not md.exists():
        return ""
    for block in md.read_text().split("\n\n"):
        b = block.strip()
        if b and not b.startswith("#"):
            return re.sub(r"\s+", " ", b)[:200]
    return ""


def collect_lessons():
    out = []
    if LESSONS.is_dir():
        for f in sorted(LESSONS.glob("*.md")):
            out.append({"name": f.stem, "hook": first_paragraph(f)})
    return out


def render(creations, patterns, lessons) -> str:
    lines = []
    lines.append("# CATALOG — the library index (generated)\n")
    lines.append("> **Generated by `scripts/build-catalog.py` — do not hand-edit.** "
                 "Regenerate after adding or renaming any asset. `agent.librarian` routes "
                 "from this file, so it must reflect what is on disk, not memory.\n")
    lines.append(f"Totals: {len(creations)} creations · {len(patterns)} patterns · "
                 f"{len(lessons)} lessons.\n")

    # Creations grouped by kind, then domain
    for kind in KIND_ORDER:
        krows = [r for r in creations if r["kind"] == kind]
        if not krows:
            continue
        lines.append(f"\n## {kind}s\n")
        domains = sorted({r["domain"] for r in krows})
        for dom in domains:
            drows = [r for r in krows if r["domain"] == dom]
            lines.append(f"\n### {dom}\n")
            for r in sorted(drows, key=lambda x: x["id"]):
                eff = f" _(effects: {r['effects']})_" if r["effects"] else ""
                lines.append(f"- **`{r['id']}`**{eff} — {r['desc']}")

    # Patterns
    if patterns:
        lines.append("\n## patterns\n")
        for p in patterns:
            lines.append(f"- **`{p['id']}`** — {p['intent']}")

    # Lessons
    if lessons:
        lines.append("\n## lessons\n")
        for l in lessons:
            lines.append(f"- **`{l['name']}`** — {l['hook']}")

    lines.append("")
    return "\n".join(lines)


def main():
    creations = collect_creations()
    patterns = collect_patterns()
    lessons = collect_lessons()
    OUT.write_text(render(creations, patterns, lessons))
    print(f"CATALOG.md: {len(creations)} creations, {len(patterns)} patterns, "
          f"{len(lessons)} lessons")


if __name__ == "__main__":
    main()
